# Generated by Django 5.1.6 on 2025-02-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
    ]
